apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jhub-shared-pvc
  namespace: jhub   
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs-client 

